apiVersion: v1
kind: Service
metadata:
  name: windowssvc
spec:
  ports:
  - port: 80 
    targetPort: 80
    protocol: TCP
  selector:
    app: winapp
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: win-deployment
spec:
  selector:
    matchLabels:
      app: winapp
  replicas: 1
  template:
    metadata:
      labels:
        app: winapp
    spec:
      containers:
      - name: winappmaincontainer
        image: jakkaj/reganasp:1 # Update the version of nginx from 1.7.9 to 1.8
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: windows

